[versions]
kotlin = "2.3.10"
th2-plugin = "0.3.14"

[libraries]
th2-common = { group = "com.exactpro.th2", name = "common", version = "5.17.2-dev" }
th2-common-utils = { group = "com.exactpro.th2", name = "common-utils", version = "2.4.0-dev" }
th2-grpc-act = { group = "com.exactpro.th2", name = "grpc-act-template", version = "4.4.0" }
th2-grpc-check1 = { group = "com.exactpro.th2", name = "grpc-check1", version = "4.5.1" }

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "8.0.01" }

th2-junit-jupiter-integration = { group = "com.exactpro.th2", name = "junit-jupiter-integration", version = "0.2.0" }
junit-bom = { group = "org.junit", name = "junit-bom", version = "5.14.2" }
strikt-core = { group = "io.strikt", name = "strikt-core", version = "0.34.1" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "6.2.3" }

[plugins]
th2-component = { id = "com.exactpro.th2.gradle.component", version.ref = "th2-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }